name: Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Patches (.mpp & .jar)
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Publish Custom Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          name: "Morphe Patches v1.0.0"
          body: "Custom build with 4-mode fullscreen video scale."
          files: |
            **/build/libs/*.mpp
            **/build/libs/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
